#%RAML 1.0
version: v1
title: football-system-api

traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string

types:
  fixture: !include fixture-schema.json
  team: !include team-schema.json

/football:
  /fixture:
    post:
      body: 
        application/json:
          schema: fixture
      responses: 
        201:
          body: 
            application/json:
              example: {"message":"Success"}
        500:
          body:
            application/json:
              example: {"message":"Failure"}
    /{fixtureId}:
      get:
        queryParameters: 
          fixtureId:
            type: string
            description: The match id of the fixture being retrieved.
        responses: 
          200:
            body:
              application/json:
                schema: fixture
          404:
            body:
              application/json:
                example: {"message" : "Invalid match id"}
            
  /tournament:
    /{tournamentId}:
  /team:
    post:
      is:  [client-id-required]
      body: 
        application/json:
          schema: team
      responses: 
        201:
          body: 
            application/json:
              example: {"message":"Success"}
        500:
          body:
            application/json:
              example: {"message":"Failure"}
    /{teamName}:
      get:
        is:  [client-id-required]
        responses:
          200:
            body:
              application/json:
                schema: team
          404:
            body:
              application/json:
                example: {"message": "Failure"}
    /manager: